### ISSUE TITLE
Vendor buildifier

### ISSUE THREAD

**Issue by TheButlah** [jlebar/pre-commit-hooks#3]
It would be awesome if the buildifier hook could download buildifier instead of assuming that it is system installed. Buildifier is a go program, so it can simply be `wget`ted from the [github repository](https://github.com/bazelbuild/buildtools/releases) with a simple check to determine whether the os is windows, mac, or linux.

**Comment by jlebar** [comment]
Agree that would be way better.

I'd be happy to take a patch, now that I'm subscribed to updates to this repo.  :)

**Comment by ScottTodd** [comment]
This worked for me, downloading buildifier from the source repo on Windows and Linux using golang bootstrapping from pre-commit 3.0.0+ (https://pre-commit.com/#golang):

```yml
-   repo: local
    hooks:
    -   id: buildifier
        name: Run buildifier
        entry: buildifier
        language: golang
        additional_dependencies: ["github.com/bazelbuild/buildtools/buildifier@1429e15ae755a6762d0edf9198062dc6ed04408d"]
        files: '^(.*/)?(BUILD\.bazel|BUILD|WORKSPACE|WORKSPACE\.bazel|WORKSPACE\.bzlmod|MODULE\.bazel)$|\.BUILD$|\.bzl$'
        language_version: "1.16"
```

* could also use the `@latest` version, but semvar tags like `v7.1.2` in the buildtools repo (https://github.com/bazelbuild/buildtools/tags) don't seem to work with `go install` (maybe related to no versions showing up on https://pkg.go.dev/github.com/bazelbuild/buildtools/buildifier?tab=versions, idk)
* I had to pin the language_version since I had an older version of `go` installed on my system that didn't support `go install`
